<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="my-request-bottom-block" data-mage-init='{"my_form_modal": {}}' >
  <input class="my-request-bottom" type="button" value="<?= __('Request price') ?>">
  <div class="pop-up">
    <form>
      <div class="block-input">
        <label for="fname"><?= __('First name: *') ?></label>
        <input type="text" id="fname" name="fname">
      </div>
      <div class="block-input">
        <label for="lname"><?= __('Last name:') ?></label>
        <input type="text" id="lname" name="lname">
      </div>
      <div class="block-input">
        <label for="emaill"><?= __('Enter your email: *') ?></label>
        <input type="email" id="emaill" name="emaill" value="">
      </div>
      <div class="block-input">
        <label for="product_name"><?= __('Product name: *') ?></label>
        <input type="text" id="product_name" name="product_ame" value="<?= $block->getProduct()->getName(); ?>" disabled>
      </div>
      <div class="block-input">
        <label for="product_sku"><?= __('*SKU:') ?></label>
        <input type="text" id="product_sku" name="product_sku" value="<?= $block->getProduct()->getSku(); ?>" disabled>
      </div>
      <input type="button" value="<?= __('Submit') ?>" />
    </form>
  </div>
</div>


