<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">

        <div class="filter-header">
            <div class="filter-header-close"></div>
        </div>
        <div class="block-title filter-title">
            <strong><?= $block->escapeHtml(__('Filter By')) ?></strong>
            <div class="block-actions filter-actions">
                <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><div class="reset-button-category"><?= $block->escapeHtml(__('Reset')) ?></div></a>
            </div>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>

            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
        <?php if (!$wrapOptions) : ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
            <dl class="filter-options" id="narrow-by-list" data-mage-init='{"accordion_category": {}}'>
                <?php $wrapOptions = true;
                endif; ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <button class="category-accordion"> <dt role="heading" aria-level="3" class="filter-options-title">
                            <?= $block->escapeHtml(__($filter->getName())) ?></dt>
                    </button>
                    <div class="panel"><dd class="filter-options-content">
                            <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd></div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions) : ?>
            </dl>
        <?php endif; ?>
        </div>
        <input class="category-button-popup" type="submit" value="<?= __('Apply filters') ?>">
    </div>
<?php endif; ?>
